[package]
name = "minecraft-loaders"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { version = "1.0.148" }
serde = { version = "1.0.228", features = ["derive"] }
reqwest = {version = "0.12.28", features = ["json"]}
anyhow = {version = "1.0.100"}
thiserror = {version = "2.0.17"}